---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      dnf:
        name: python-pip
        state: present
    - name: Install docker
      dnf:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: hariapp
        image: "mukesh92/hariapp:0.0.1"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
